### ISSUE TITLE
Unhandled Rejection (TypeError): excalidrawRef.current is null

### ISSUE THREAD

**Issue by wayne9499** [wayne9499/react-excalidraw-app#5]
# Whenever using setInterval for auto saving, in the ui following screen with the written error appears, although despire the error auto-saving api is doing good. (should do debugging for this)
<img width="958" alt="issue-1" src="https://user-images.githubusercontent.com/53325994/126077499-e8fe4fdd-3b21-4fba-8b30-bf9ed94d2716.PNG">

**Comment by drj-sharma** [comment]
resolved by the previous PRs!!
